name: Python 3 test

on: [push]

jobs:
  test:

    runs-on: continuumio/miniconda3
    strategy:
      max-parallel: 3


    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Test with TOX
        run: |
          tox -p 3
      - name: Cache tox
        uses: actions/cache@v3.0.2
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: .tox
          # An explicit key for restoring and saving the cache
          key: tox-folder


